name       : borg
version    : 1.1.0
release    : 6
source     :
    - https://github.com/borgbackup/borg/releases/download/1.1.0/borgbackup-1.1.0.tar.gz : b40c1120c480a8235ce403b8e6e7abf1377458896f438eafce60f54916789e6f
license    : BSD-3-Clause
component  : system.utils
summary    : A deduplicating backup program
description: |
    BorgBackup (short: Borg) is a deduplicating backup program.
    Optionally, it supports compression and authenticated encryption.
    The main goal of Borg is to provide an efficient and secure way to backup data.
    The data deduplication technique used makes Borg suitable for daily backups since only changes are stored.
    The authenticated encryption technique makes it suitable for backups to not fully trusted targets.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(liblz4)
    - pkgconfig(python-3.5)
    - acl-devel
    - cython
    - pycrypto
    - python-distutils-extra
    - python-llfuse
    - python-setuptools-scm
rundeps    :
    - python-llfuse
    - python-msgpack
build      : |
    %python3_setup
install    : |
    %python3_install
