name       : borg
version    : 1.1.14
release    : 24
source     :
    - https://github.com/borgbackup/borg/releases/download/1.1.14/borgbackup-1.1.14.tar.gz : 7dbb0747cc948673f695cd6de284af215f810fed2eb2a615ef26ddc7c691edba
license    : BSD-3-Clause
component  : system.utils
homepage   : https://www.borgbackup.org/
summary    : A deduplicating backup program
description: |
    BorgBackup (short: Borg) is a deduplicating backup program.
    Optionally, it supports compression and authenticated encryption.
    The main goal of Borg is to provide an efficient and secure way to backup data.
    The data deduplication technique used makes Borg suitable for daily backups since only changes are stored.
    The authenticated encryption technique makes it suitable for backups to not fully trusted targets.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(liblz4)
    - pkgconfig(libzstd)
    - pkgconfig(python3)
    - acl-devel
    - cython
    - python-distutils-extra
    - python-llfuse
    - python-msgpack  # check
    - python-pytest   # check
    - python-setuptools-scm
rundeps    :
    - python-llfuse
    - python-msgpack
build      : |
    # Can be removed in version 1.2.0
    sed -i 's/msgpack-python/msgpack/' setup.py

    %python3_setup
install    : |
    %python3_install

    install -D -m00644 scripts/shell_completions/bash/borg $installdir/usr/share/bash-completion/completions/borg
    install -D -m00644 scripts/shell_completions/zsh/_borg $installdir/usr/share/zsh/site-functions/_borg
    install -D -m00644 docs/man/*.1 -t $installdir/usr/share/man/man1/
check      : |
    export PYTHONPATH=$PKG_BUILD_DIR/py3build/build/lib.linux-x86_64-%python3_version%
    %python3_test py.test3 -vk "not test_non_ascii_acland and not test_fuse and not benchmark and not test_dash_open and not test_basic_functionality" $PYTHONPATH/borg/testsuite/*.py
