name       : borg
version    : 1.0.9
release    : 1
source     :
    - https://github.com/borgbackup/borg/releases/download/1.0.9/borgbackup-1.0.9.tar.gz : 35860840e0429d4bb3acc8b9dd33aa5996a42fb2b678813a982b321a7dba3cb2
license    : BSD-3-Clause
component  : system.utils
summary    : A deduplicating backup program
description: |
    BorgBackup (short: Borg) is a deduplicating backup program.
    Optionally, it supports compression and authenticated encryption.
    The main goal of Borg is to provide an efficient and secure way to backup data.
    The data deduplication technique used makes Borg suitable for daily backups since only changes are stored.
    The authenticated encryption technique makes it suitable for backups to not fully trusted targets.
builddeps  :
    - pkgconfig(liblz4)
    - acl-devel
    - cython
    - pycrypto
    - python-distutils-extra
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
