name       : borg
version    : 1.1.2
release    : 8
source     :
    - https://github.com/borgbackup/borg/releases/download/1.1.2/borgbackup-1.1.2.tar.gz : 097b2d92d51f570aaea82ab6632481b8235b78d7bbaac9d8164bdfa6bd5b5502
license    : BSD-3-Clause
component  : system.utils
summary    : A deduplicating backup program
description: |
    BorgBackup (short: Borg) is a deduplicating backup program.
    Optionally, it supports compression and authenticated encryption.
    The main goal of Borg is to provide an efficient and secure way to backup data.
    The data deduplication technique used makes Borg suitable for daily backups since only changes are stored.
    The authenticated encryption technique makes it suitable for backups to not fully trusted targets.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(liblz4)
    - pkgconfig(python-3.5)
    - acl-devel
    - cython
    - pycrypto
    - python-distutils-extra
    - python-llfuse
    - python-setuptools-scm
rundeps    :
    - python-llfuse
    - python-msgpack
build      : |
    %python3_setup
install    : |
    %python3_install
